version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: telco_bss
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
volumes:
  db_data:
